### ISSUE TITLE
[課程] 第一次觀看「課程課程評價」，出現錯誤訊息

### ISSUE THREAD

**Issue by paperhsiaooo** [HSNM2/backend-nodejs#38]
![Image](https://github.com/HSNM2/backend-nodejs/assets/127862412/ec39a439-0e02-4c69-9197-e7eec7ec1138)
![Image](https://github.com/HSNM2/backend-nodejs/assets/127862412/9fea0232-445a-4393-a2e0-ce73acbd0c7b)
![Image](https://github.com/HSNM2/backend-nodejs/assets/127862412/a10453aa-438c-4540-857e-963c5895c231)
![Image](https://github.com/HSNM2/backend-nodejs/assets/127862412/191252fa-f40a-4d34-8498-4ce944569059)

問題：
1. 進入單一課程資訊後，如果先前從未點擊過課程評價，點擊後則會出現「發生錯誤」之訊息
2. 查看後端 log 後，應是後端發生 error

**Comment by ankazu** [comment]
![Image](https://github.com/HSNM2/backend-nodejs/assets/17851255/4c717cec-f3f0-48e0-b4e6-d5842b66976d)

課程 1 會產生錯誤，進入課程詳細頁是空的，目前判斷上圖發生錯誤是取得課程 1 導致。

**Comment by ankazu** [comment]
![Image](https://github.com/HSNM2/backend-nodejs/assets/17851255/8bebf0b3-e46d-4d1c-abe4-c04812fddaea)

目前網頁發生的錯誤

**Comment by ankazu** [comment]
兩支 rating api 
ratings 多加了 token 驗證，已移除，測試正常。
rating 與 ownedCourse/check 這兩支 get api ，目前判斷是前台未判斷是否為登入狀態下呼叫所導致錯誤。
profile get api 也是需要登入後才呼叫

**Comment by meijun17** [comment]
rating 與 ownedCourse/check 這兩支已修正。
profile 這支目前是前端判斷是否有登入，所以沒改。
